baseurl = "http://kellyripple.com"
DefaultContentLanguage = "en"
title = "Kelly Ripple"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#googleAnalytics = "XXX"

[Params]
  homeTitle = "Blog" 
  subtitle = ""
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  logo = "img/avatar-icon.png"
  commit = false
  rss = false
  comments = true
  readingTime = true
  useHLJS = true
  socialShare = false
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Kelly Ripple"
  website = "kellyripple.com"
  email = "kelly.ripple@bti360.com"
  github = "kripple"
  twitter = "krippleffect"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

 [[menu.main]]
    name = "Projects"
    url = "/project"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 3
